# Generated by Django 3.2.13 on 2024-03-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20240228_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancalculator',
            name='ltc',
            field=models.FloatField(default=0.0),
        ),
    ]
