# Generated by Django 3.2.13 on 2024-03-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_stockfilelog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='jd_power_clean_retail_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='jd_power_clean_retail_value',
            field=models.IntegerField(default=0),
        ),
    ]
